# Generated by Django 3.1.6 on 2021-02-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_type', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(blank='False', max_length=250)),
                ('evolution_level', models.IntegerField(null=True)),
                ('next_evolution', models.CharField(max_length=250, null=True)),
                ('pokemon_type', models.ManyToManyField(blank='False', to='pokemon.PokemonType')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=250)),
                ('level', models.IntegerField(null=True)),
                ('trainer', models.CharField(max_length=250, null=True)),
                ('species', models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemonspecie')),
            ],
        ),
    ]
