# Generated by Django 3.1.6 on 2021-02-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20210208_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecie',
            name='pokemon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemontype'),
        ),
    ]
