# Generated by Django 3.1.6 on 2021-02-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_auto_20210208_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemontype',
            old_name='pokemon_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pokemonspecie',
            name='pokemon_type',
        ),
        migrations.AddField(
            model_name='pokemonspecie',
            name='pokemon_type',
            field=models.ManyToManyField(to='pokemon.PokemonType'),
        ),
    ]
