# Generated by Django 3.1.6 on 2021-02-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20210208_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonspecie',
            old_name='pokemon_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pokemonspecie',
            old_name='pokemon_type',
            new_name='pokemon_types',
        ),
    ]
