# Generated by Django 3.1.6 on 2021-02-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_auto_20210208_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonspecie',
            old_name='pokemon_types',
            new_name='show_type',
        ),
    ]
