# Generated by Django 3.1.6 on 2021-02-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_auto_20210208_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecie',
            name='evolution_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecie',
            name='name',
            field=models.CharField(blank='False', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonspecie',
            name='show_type',
            field=models.ManyToManyField(to='pokemon.PokemonType', verbose_name='pokemon types'),
        ),
    ]
