# Generated by Django 3.1.6 on 2021-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_auto_20210208_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecie',
            name='next_evolution',
            field=models.CharField(max_length=200),
        ),
    ]
