# Generated by Django 3.1.6 on 2021-02-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_auto_20210208_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='nickname',
        ),
    ]
