# Generated by Django 3.1.6 on 2021-02-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_auto_20210208_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='species',
            new_name='specie',
        ),
    ]
