# Generated by Django 3.1.6 on 2021-02-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0015_auto_20210208_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecie',
            name='next_evolution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
