# Generated by Django 3.1.6 on 2021-02-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0017_auto_20210208_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecie',
            name='evolution_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
