# Generated by Django 3.1.6 on 2021-02-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0018_auto_20210208_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonspecie',
            old_name='show_type',
            new_name='pokemon_type',
        ),
    ]
