# Generated by Django 3.1.6 on 2021-02-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0019_auto_20210208_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='specie',
            new_name='species',
        ),
        migrations.AlterField(
            model_name='pokemonspecie',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
